hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

reward_model:
  reward_manager: collabllm

trainer:
  project_name: verl-collabllm

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: vllm
    multi_turn:
      enable: True
      max_user_turns: 1
      max_assistant_turns: 3
      num_repeat_rollouts: 2 
      format: hermes
